### PR TITLE
Updating default jira version to 8.20.13

### LINKED ISSUE #452: [Suggestion] - Bump Default Jira Version
### Suggestion

Hello, 

Could a new helm chart be cut for version `8.20.13`

The default value which is `8.20.10`(Released 23 June 2022) has the following security findings that have been fixed in `8.20.13` (21 September 2022)

[JRASERVER-73597](https://jira.atlassian.com/browse/JRASERVER-73597?src=confmacro)
[JRASERVER-73738](https://jira.atlassian.com/browse/JRASERVER-73738?src=confmacro)
[JRASERVER-73593](https://jira.atlassian.com/browse/JRASERVER-73593?src=confmacro)

~I can create a pull request if you would like, I can use this pull request as a template #430~

Created a PR #453 

Thank you ! 

Temp workaround, hardcode the tag in the `helm-values.yml`

### Product

Jira

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jeremy-Boyle**
## Pull request description

Fixes #452 ,

bumps default version to `8.20.13` for security patches 

## Checklist
- [x] I have added unit tests
- [x] I have applied the change to all applicable products
- [x] I have added the change description to the `changelog.md` and `Chart.yaml` files
- [ ] (Atlassian only) I have run the E2E test (if applicable)
- [ ] (Atlassian only) Internal Bamboo CI is passing

### CODE REVIEW

**Comment by yzha645** [comment]
Hi @Jeremy-Boyle , thanks for the contribution! 
Do you mind fixing the unit tests as well?

**Comment by Jeremy-Boyle** [comment]
Hi I sure can ! Thanks for the review, I see it's failing on a maven issue, I'll take a look to see what is causing it however all other things deployed correctly, what is the purpose of the maven test with a helm chart ? 

Is the error related to my changes ?

**Comment by yzha645** [comment]
> Hi I sure can ! Thanks for the review, I see it's failing on a maven issue, I'll take a look to see what is causing it however all other things deployed correctly.

Awesome, @Jeremy-Boyle ~ 
Here is code as reference: https://github.com/atlassian/data-center-helm-charts/pull/455/files#diff-63ea51911cc0f4498740fb7f8ee9bba6524a8c59bf6378ae51489847c9178444 
In your case, src/test/resources/expected_helm_output/jira/output.yaml needs to be updated to the newer version.

**Review by yzha645 — DISMISSED** [review]

**Review by nghazali — CHANGES_REQUESTED** [review]
Unit test is failed!

**Comment by yzha645** [comment]
Hi @Jeremy-Boyle , just two minor issues to be fixed for the unit test: https://github.com/atlassian/data-center-helm-charts/actions/runs/3183460733/jobs/5198287045#step:11:1018 

And also, do you mind pulling the latest main into your branch as well? Cheers~

**Review by yzha645 — APPROVED** [review]

**Review by nghazali — APPROVED** [review]

**Pull request merged**
