### PR TITLE
Ingress Class Name is moved under spec field.

### PR DESCRIPTION
**Pull request by kyunam-jo**
After Kubernetes 1.18 version, "ingress.class"'s annotation is deprecated.
So deleted that annotation and add "ingressClassName" field.

ref: https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation

## Pull request description

_Provide description for the PR_

## Checklist
- [x] I have added unit tests
- [x] I have applied the change to all applicable products
- [x] I have added the change description to the `changelog.md` and `Chart.yaml` files
- [ ] (Atlassian only) I have run the E2E test (if applicable)
- [ ] (Atlassian only) Internal Bamboo CI is passing

### CODE REVIEW

**Comment by kyunam-jo** [comment]
> Thank you for your submission! Like many open source projects, we ask that you sign our [CLA (Contributor License Agreement)](https://opensource.atlassian.com/cla) before we can accept your contribution. **If your email is listed below**, please ensure that you sign the CLA with the **same email address**. **The following users still need to sign our CLA:**❌[kyunam.jo@sk.com](mailto:kyunam.jo@sk.com)
> 
> Already signed the CLA? To re-check, try refreshing the page.

I already signed.....

**Comment by nanux** [comment]
@kyunam-jo, thank you for your contribution.

Could you please fix the unit tests and verify the new `ingressClassName` spec field?

As the `nginx` is the default value in the `values.yaml` file, is it still necessary to default it in the expression?

**Review by nanux — CHANGES_REQUESTED** [review]
@kyunam-jo, thank you for your contribution.

Could you please fix the unit tests and verify the new `ingressClassName` spec field?

As the `nginx` is the default value in the `values.yaml` file, is it still necessary to default it in the expression?

**Comment by kyunam-jo** [comment]
> Could you please fix the unit tests and verify the new `ingressClassName` spec field?
> 
> As the `nginx` is the default value in the `values.yaml` file, is it still necessary to default it in the expression?

Oh. I missed unit test ... fixed unit test error in IngressTest.java
and I think that no more necessary to check default value in 'ingress_create', but when ingressClassName is changed, it is necessary.

**Comment by yzha645** [comment]
Hi @kyunam-jo , looks like the unit test is still failing. Are you able to have another look at it? Cheers.
https://github.com/atlassian/data-center-helm-charts/actions/runs/3137537652/jobs/5198195070

**Comment by kyunam-jo** [comment]
> Hi @kyunam-jo , looks like the unit test is still failing. Are you able to have another look at it? Cheers. https://github.com/atlassian/data-center-helm-charts/actions/runs/3137537652/jobs/5198195070

Oh I'm sorry. I checked unit test. 
Could you re-run unit test workflow?

**Comment by nanux** [comment]
@kyunam-jo the unit test is passing, I have also kicked off end to end test and updated the changelogs. This is ready to go.

**Review by nanux — DISMISSED** [review]

**Comment by kyunam-jo** [comment]
@nanux thanks for your commit and reviewing 😁

**Review by jjeongatl — DISMISSED** [review]

**Review by bianchi2 — APPROVED** [review]

**Review by nanux — COMMENTED** [review]
Update the chart version

**Review by nanux — APPROVED** [review]

**Comment by kyunam-jo** [comment]
@nanux Thanks for your help. 👍

**Pull request merged**
