### PR TITLE
Update Atlassian charts to use common definitions

### PR DESCRIPTION
**Pull request by hickeyma**
Update the charts to use the follow common definitions from the common chart:

- `fullname`
- `name`
- `chart`
- `selectorLabels`
- `labels` 

Signed-off-by: Martin Hickey <martin.hickey@ie.ibm.com>

Partial #302 

~~__Note: This PR depends on #358. DO NOT MERGE until #358 is merged.__~~ #358 now merged and common chart released..

### CODE REVIEW

**Comment by nanux** [comment]
@hickeyma, I have tested the changes locally and updated the PR to update the remaining references. The tests are also passing now.

I think the change is useful but it will have an impact on developer experience. What do you think is the best approach? Should we add a target to `Makefile` to run `helm dependency update` over the helm charts so people can easily init or update the common chart? Does the helm chart have an impact on the release cycle? From my local testing, after the dependency initialization, the `common` is stored in `charts` subfolder in each product helm chart and then included in `helm package` command, which is the desired behavior. I just wonder if there are other aspects we should consider before merging this change.

**Comment by hickeyma** [comment]
> I have tested the changes locally and updated the PR to update the remaining references. The tests are also passing now. I hope it is ok, that I was working on your branch, I think it will save time for everybody.

Not a bother. Thanks for the updates @nanux.

> I think the change is useful but it will have an impact on developer experience. What do you think is the best approach? Should we add a target to Makefile to run helm dependency update over the helm charts so people can easily init or update the common chart?

I think you are best suited to decide for chart maintainers. The impact is quite negligible as the chart maintainer will get the error message straight off: `Error: INSTALLATION FAILED: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: common`.  But as I have said, I think you are best placed to decide this.

> Does the helm chart have an impact on the release cycle?

What impact do you forsee?

> I just wonder if there are other aspects we should consider before merging this change.

That's a good point. I just thought about how we referenced the chart using file over repo reference. I have extracted the common chart into #358 as I think we should merge this first so it is part of the chart repository.  It can then be referenced as follows:

```yaml
dependencies:
   - name: common
     version: 1.0.0
     repository: https://atlassian.github.io/data-center-helm-charts
```
This is the more standard way to do it.

**Comment by hickeyma** [comment]
@nanux Looks like the `common` chart is not added to the Atlassian chart repository yet. Would you be able to look into this?

**Comment by nanux** [comment]
@hickeyma, yes. I am preparing the release for other products as well and as part of it, I will release the `common` chart.

**Comment by hickeyma** [comment]
Great, thanks @nanux

**Comment by nanux** [comment]
@hickeyma, the `common-1.0.0` chart was released, can you please continue with this PR?

Thank you

**Comment by hickeyma** [comment]
@nanux Thanks for releasing the common chart. Updated the PR with the released common chart. Ready for review again.

**Comment by hickeyma** [comment]
@nanux Do you mind doing a review when you get a chance? It would be good to get this merged to start using the common chart definitions.

**Comment by nanux** [comment]
@hickeyma, I have added the necessary commands to our testing scripts to make it work in our CI as well. Since morning we did release bamboo 1.0.0 and a couple of other improvements for all the charts resulting in some conflicts. I have tried to fix the conflicts locally but git struggled with the fork remote. Could you please fix the conflicts and then I believe we are ready to merge.

Thank you! 🥇

**Comment by hickeyma** [comment]
@nanux Thanks for adding the updates to the testing scripts. I have merged the conflicts and it is ready for review again.

**Review by nghazali — APPROVED** [review]

**Review by jjeongatl — APPROVED** [review]

**Review by yzha645 — APPROVED** [review]

**Comment by nghazali** [comment]
Thank you @hickeyma , All good. we had another recent commit which caused some more conflicts in this PR. I just resolved them and merged the PR. Thank you again for the awesome suggestion and work 🥇

**Comment by hickeyma** [comment]
Thanks @nanux @nghazali @yzha645 @jjeongatl for reviewing. Thanks @nghazali for merging.

Its great to see this capability in place and should help streamline chart maintenance.

**Pull request merged**
